-- Información general generada automáticamente
INSERT INTO fragmentos_conocimiento (contenido, categoria, facultad, palabras_clave) VALUES ('La Universidad Nacional de Salta organiza un espacio para acercar ciencia, innovación y tecnología a toda la comunidad.', 'General', 'General', ARRAY['nacional', 'innovación', 'comunidad', 'acercar', 'salta', 'organiza', 'espacio', 'universidad']);
INSERT INTO fragmentos_conocimiento (contenido, categoria, facultad, palabras_clave) VALUES ('Ingreso 2026 - Fechas de preinscripción:', 'Inscripción', 'General', ARRAY['fechas', 'ingreso', 'preinscripción']);
INSERT INTO fragmentos_conocimiento (contenido, categoria, facultad, palabras_clave) VALUES ('- Del 1 de octubre de 2025 al 31 de enero de 2026 para todas las carreras.', 'General', 'General', ARRAY['octubre', 'enero', 'carreras', 'todas']);
INSERT INTO fragmentos_conocimiento (contenido, categoria, facultad, palabras_clave) VALUES ('- Carrera de Medicina: del 1 de octubre al 14 de diciembre de 2025.', 'General', 'General', ARRAY['medicina', 'octubre', 'carrera', 'diciembre']);
INSERT INTO fragmentos_conocimiento (contenido, categoria, facultad, palabras_clave) VALUES ('Contacto Universidad Nacional de Salta:', 'Contacto', 'General', ARRAY['salta', 'contacto', 'nacional', 'universidad']);
INSERT INTO fragmentos_conocimiento (contenido, categoria, facultad, palabras_clave) VALUES ('- Dirección: Av. Bolivia 5150, Salta, CP 4400, Argentina', 'Ubicación', 'General', ARRAY['bolivia', 'dirección', 'salta', 'argentina']);
INSERT INTO fragmentos_conocimiento (contenido, categoria, facultad, palabras_clave) VALUES ('- Email: webunsa@unsa.edu.ar', 'Contacto', 'General', ARRAY['webunsa', 'unsa', 'email']);
INSERT INTO fragmentos_conocimiento (contenido, categoria, facultad, palabras_clave) VALUES ('- Sitio web UNSa: https://www.unsa.edu.ar', 'Contacto', 'General', ARRAY['https', 'unsa', 'sitio']);
INSERT INTO fragmentos_conocimiento (contenido, categoria, facultad, palabras_clave) VALUES ('- Sitio web Facultad de Ciencias Exactas: https://exactas.unsa.edu.ar', 'Contacto', 'Exactas', ARRAY['exactas', 'https', 'ciencias', 'unsa', 'sitio', 'facultad']);
INSERT INTO fragmentos_conocimiento (contenido, categoria, facultad, palabras_clave) VALUES ('Calendario Académico 2026:1er CUATRIMESTRE
Del 16/03/2026 al 26/06/2026. Presentación de Planillas: hasta el 30/06/2026', 'Calendario', 'General', ARRAY['calendario', 'académico']);
INSERT INTO fragmentos_conocimiento (contenido, categoria, facultad, palabras_clave) VALUES ('Exámenes en la Facultad de Ciencias Exactas: Turnos Ordinarios:
Julio - Agosto de 2026 1er Llamado: 06, 07, 08/07/2026 2do Llamado: 03, 04, 05/08/2026. Diciembre de 2026: 1er Llamado: 03, 04/12/2026 2do Llamado: 16, 17, 18/12/2026', 'Calendario', 'Exactas', ARRAY['exámenes', 'ciencias', 'facultad', 'exactas']);
INSERT INTO fragmentos_conocimiento (contenido, categoria, facultad, palabras_clave) VALUES ('La Facultad de Ciencias Exactas en sede Central ofrece la carrera de posgrado: Maestría en Energías Renovables.', 'Ubicación', 'Exactas', ARRAY['energías', 'exactas', 'maestría', 'carrera', 'renovables', 'posgrado', 'ciencias', 'sede']);
INSERT INTO fragmentos_conocimiento (contenido, categoria, facultad, palabras_clave) VALUES ('La Facultad de Ciencias Exactas en sede Central ofrece la carrera de posgrado: Especialización en Energías Renovables.', 'Ubicación', 'Exactas', ARRAY['energías', 'exactas', 'carrera', 'renovables', 'posgrado', 'ciencias', 'sede', 'central']);
INSERT INTO fragmentos_conocimiento (contenido, categoria, facultad, palabras_clave) VALUES ('La Facultad de Ciencias Exactas en sede Central ofrece la carrera de posgrado: Maestría en Matemática Aplicada.', 'Ubicación', 'Exactas', ARRAY['aplicada', 'exactas', 'maestría', 'matemática', 'carrera', 'posgrado', 'ciencias', 'sede']);
INSERT INTO fragmentos_conocimiento (contenido, categoria, facultad, palabras_clave) VALUES ('La Facultad de Ciencias Exactas en sede Central ofrece la carrera de posgrado: Doctorado en Ciencias – Área Química Aplicada.', 'Ubicación', 'Exactas', ARRAY['aplicada', 'exactas', 'carrera', 'química', 'posgrado', 'ciencias', 'sede', 'central']);
INSERT INTO fragmentos_conocimiento (contenido, categoria, facultad, palabras_clave) VALUES ('La Facultad de Ciencias Exactas en sede Central ofrece la carrera de posgrado: Doctorado en Ciencias – Área Energías Renovables.', 'Ubicación', 'Exactas', ARRAY['energías', 'exactas', 'carrera', 'renovables', 'posgrado', 'ciencias', 'sede', 'central']);
INSERT INTO fragmentos_conocimiento (contenido, categoria, facultad, palabras_clave) VALUES ('Contacto de UNSa: Dirección: Av. Bolivia 5150, Salta, CP 4400, Argentina Email: webunsa@unsa.edu.ar Sitio web: https://www.unsa.edu.ar', 'Contacto', 'General', ARRAY['bolivia', 'salta', 'https', 'contacto', 'unsa', 'sitio', 'webunsa', 'dirección']);
INSERT INTO fragmentos_conocimiento (contenido, categoria, facultad, palabras_clave) VALUES ('Contacto de Facultad de Ciencias Exactas: Sitio web: https://exactas.unsa.edu.ar', 'Contacto', 'Exactas', ARRAY['exactas', 'https', 'contacto', 'ciencias', 'unsa', 'sitio', 'facultad']);
INSERT INTO fragmentos_conocimiento (contenido, categoria, facultad, palabras_clave) VALUES ('Beca: Beca de Apoyo Académico. Requisitos: Estar inscripto regularmente, promedio mayor a 6, y presentar documentación socioeconómica. Inscripción abre el 2026-03-01. Más info: https://www.unsa.edu.ar/becas', 'Contacto', 'General', ARRAY['mayor', 'requisitos', 'académico', 'apoyo', 'estar', 'becas', 'socioeconómica', 'documentación']);
